import React from 'react';
import { FileText, Printer, CheckCircle2 } from 'lucide-react';
import { TRADE_ROUTES } from '../../data/tradeRoutesData';
import { EAST_COAST_INDIAN_PORTS } from '../../data/portsData';
import { VesselType } from '../../types/maritime';

interface ExportReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  vesselType?: VesselType;
  volumeMT?: number;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({ 
  isOpen, 
  onClose,
  vesselType = 'Panamax',
  volumeMT = 600000
}) => {
  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-white p-6 sm:p-8 rounded-3xl border border-slate-200 max-w-3xl w-full shadow-2xl space-y-6 my-8">
        
        {/* Header Controls */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-100">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-orange-600" />
            <div>
              <h3 className="text-lg font-display font-bold text-slate-900">
                Executive Chartering &amp; Freight Intelligence Brief
              </h3>
              <span className="text-[10px] font-mono text-slate-500 font-semibold">
                Generated by Vedha Logistics AI • September 2026
              </span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold text-slate-700 bg-slate-100 hover:bg-slate-200 border border-slate-300 cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>
            <button
              onClick={onClose}
              className="text-slate-400 hover:text-slate-900 p-2 rounded-lg bg-slate-100 cursor-pointer text-xs font-bold"
            >
              ✕
            </button>
          </div>
        </div>

        {/* Report Content */}
        <div className="space-y-6 text-xs text-slate-800">
          
          {/* Executive Summary Card */}
          <div className="p-5 rounded-2xl bg-slate-50 border border-slate-200 space-y-2">
            <span className="font-bold text-orange-600 uppercase text-[10px] font-mono block">
              1. Strategic Transition Recommendation
            </span>
            <h4 className="text-sm font-bold text-slate-900 font-display">
              Lock 6-Month COA Strategy for {volumeMT.toLocaleString()} MT Annual Met Coal Import Program
            </h4>
            <p className="text-slate-600 leading-relaxed text-[11px]">
              Recommendation: Execute structured 6-month Contract of Affreightment (COA) with designated laycan windows. Yields an estimated 13.5% landed freight savings ($1.4M / ₹12.6 Cr) against unhedged spot fixtures while eliminating seasonal demurrage spikes at Paradip and Haldia.
            </p>
          </div>

          {/* Key Parameters Table */}
          <div className="space-y-2">
            <span className="font-bold text-slate-900 uppercase text-[10px] font-mono block">
              2. Core Program Allocation Parameters
            </span>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs font-mono">
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
                <span className="text-slate-500 text-[10px] block">Vessel Class</span>
                <span className="font-bold text-slate-900">{vesselType} Bulker</span>
              </div>
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
                <span className="text-slate-500 text-[10px] block">Annual Volume</span>
                <span className="font-bold text-slate-900">{volumeMT.toLocaleString()} MT</span>
              </div>
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
                <span className="text-slate-500 text-[10px] block">Discharge Port</span>
                <span className="font-bold text-slate-900">Paradip / Dhamra</span>
              </div>
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
                <span className="text-slate-500 text-[10px] block">Bunker Clause</span>
                <span className="font-bold text-emerald-700">±$25/MT Singapore</span>
              </div>
            </div>
          </div>

          {/* BIMCO Terms Summary */}
          <div className="p-4 rounded-xl border border-slate-200 space-y-2">
            <span className="font-bold text-slate-900 text-xs block">
              3. BIMCO Contract Terms &amp; Demurrage Collar
            </span>
            <ul className="space-y-1.5 text-[11px] text-slate-600 list-disc list-inside">
              <li>Demurrage Rate capped at $19,000 / day with 72h NOR notice credit.</li>
              <li>Virtual Arrival clause activated: 0.5 MT/day bunker savings credited to charterer.</li>
              <li>Tidal high-water window coordination clause for draft-restricted berths.</li>
            </ul>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="pt-4 border-t border-slate-100 flex items-center justify-between text-xs text-slate-500 font-mono">
          <span>Confidential • Prepared for Maritime Procurement Committee</span>
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-slate-900 text-white font-bold text-xs hover:bg-slate-800 transition-colors cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
