import React from 'react';
import { FileText, Printer } from 'lucide-react';
import { TRADE_ROUTES } from '../../data/tradeRoutesData';
import { EAST_COAST_INDIAN_PORTS } from '../../data/portsData';

interface ExportReportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-white p-6 sm:p-8 rounded-3xl border border-slate-200 max-w-3xl w-full shadow-2xl space-y-6 my-8">
        
        {/* Header Controls */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-100">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-orange-600" />
            <div>
              <h3 className="text-lg font-display font-bold text-slate-900">
                Executive Chartering & Freight Intelligence Brief
              </h3>
              <span className="text-[10px] font-mono text-slate-500 font-semibold">
                Generated by Vedha Nautical AI • September 2026
              </span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold text-slate-700 bg-slate-100 hover:bg-slate-200 border border-slate-300 cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>
            <button
              onClick={onClose}
              className="text-slate-400 hover:text-slate-900 p-2 rounded-lg bg-slate-100 cursor-pointer text-xs font-bold"
            >
              ✕
            </button>
          </div>
        </div>

        {/* Report Content */}
        <div className="space-y-6 text-xs text-slate-800">
          
          {/* Executive Summary Card */}
          <div className="p-5 rounded-2xl bg-slate-50 border border-slate-200 space-y-2">
            <span className="font-bold text-orange-600 uppercase text-[10px] font-mono block">
              1. Strategic Transition Recommendation
            </span>
            <p className="leading-relaxed text-slate-700">
              Bulk cargo procurement to India's East Coast ports (Paradip, Vizag, Gangavaram, Dhamra, Haldia) should immediately transition from single spot voyage fixtures to <strong>6-Month Multiple Voyage Contracts of Affreightment (COAs)</strong>.
            </p>
            <div className="grid grid-cols-3 gap-3 pt-2 font-mono text-[11px]">
              <div className="bg-white p-3 rounded-xl border border-slate-200">
                <span className="text-slate-500 block text-[10px] font-bold">Projected Cost Delta</span>
                <span className="font-extrabold text-emerald-700 text-sm">13.5% - 18.5% / MT</span>
              </div>
              <div className="bg-white p-3 rounded-xl border border-slate-200">
                <span className="text-slate-500 block text-[10px] font-bold">Demurrage Shield Cap</span>
                <span className="font-extrabold text-sky-700 text-sm">$18,500 / Day</span>
              </div>
              <div className="bg-white p-3 rounded-xl border border-slate-200">
                <span className="text-slate-500 block text-[10px] font-bold">Draft Violation Risk</span>
                <span className="font-extrabold text-purple-700 text-sm">0.0% (Automated)</span>
              </div>
            </div>
          </div>

          {/* Key Port Constraints */}
          <div>
            <h4 className="font-bold text-slate-900 uppercase text-[11px] font-mono mb-2">
              2. East Coast Indian Port Maximum Draft & Berthing Rules
            </h4>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-[11px] font-mono">
              {EAST_COAST_INDIAN_PORTS.slice(0, 4).map(p => (
                <div key={p.id} className="p-3 rounded-xl bg-slate-50 border border-slate-200">
                  <span className="font-bold text-slate-900 block">{p.name.replace(' Port', '')}</span>
                  <span className="text-sky-700 font-bold">Max Draft: {p.maxDraft}m</span>
                  <span className="text-slate-500 block text-[10px]">{p.cargoHandlingRateTPD.toLocaleString()} TPD</span>
                </div>
              ))}
            </div>
          </div>

          {/* Forward Rates Table */}
          <div>
            <h4 className="font-bold text-slate-900 uppercase text-[11px] font-mono mb-2">
              3. 180-Day Benchmark Freight Projections
            </h4>
            <table className="w-full text-left text-[11px] font-mono bg-slate-50 rounded-xl overflow-hidden border border-slate-200">
              <thead>
                <tr className="border-b border-slate-200 text-slate-600 text-[10px] bg-slate-100">
                  <th className="p-2.5 font-bold">Procurement Corridor</th>
                  <th className="p-2.5 font-bold">Vessel Fit</th>
                  <th className="p-2.5 font-bold">Spot $/t</th>
                  <th className="p-2.5 font-bold">6M COA $/t</th>
                  <th className="p-2.5 font-bold text-emerald-700">Net Dollar Delta</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 font-medium">
                {TRADE_ROUTES.slice(0, 4).map(r => (
                  <tr key={r.id} className="bg-white">
                    <td className="p-2.5 text-slate-900 font-bold">{r.originCountry} → {r.destinationPortName}</td>
                    <td className="p-2.5 text-slate-600">Capesize / Panamax</td>
                    <td className="p-2.5 text-slate-500 font-bold">${r.spotRatePerTonUSD.toFixed(2)}</td>
                    <td className="p-2.5 text-sky-700 font-bold">${r.projected6MoRatePerTonUSD.toFixed(2)}</td>
                    <td className="p-2.5 text-emerald-700 font-bold">
                      -${(r.spotRatePerTonUSD - r.projected6MoRatePerTonUSD).toFixed(2)}/t
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Confirmation */}
          <div className="pt-4 border-t border-slate-100 flex items-center justify-between text-slate-500 text-[10px] font-semibold">
            <span>Validated by Vedha Maritime Analytics Suite</span>
            <span className="font-mono text-slate-700">Confidential • For Internal Chartering Committee Use</span>
          </div>

        </div>

      </div>
    </div>
  );
};
